[project]
name = "comfyui-model-merge-cosmos-predict-2-2b-slerp"
description = "Manage models: browsing, download and delete. Fork of ComfyUI-Model-Manager with improved HF/Civitai auth, huggingface_hub integration, and bug fixes."
version = "1.1.1"
license = { file = "LICENSE" }
dependencies = [
    "markdownify",
    "huggingface_hub>=0.25.0",
    "hf_xet>=1.0.0"
]

[project.urls]
Repository = "https://github.com/rikunarita/ComfyUI-Model-Manager-Neo"

[tool.comfy]
PublisherId = "rikunarita7669"
DisplayName = "ComfyUI-Model-Manager-Neo"
Icon = ""

[tool.black]
line-length = 160
